name: push image [FILE_NAME]

on:
  push:
    branches: 
      - publish

env:
  SOURCE_IMAGE_NAME: [SOURCE_IMAGE_NAME]
  TARGET_IMAGE_NAME: [TARGET_IMAGE_NAME]
  DOCKERHUB_USERNAME: [DOCKERHUB_USERNAME]
  DOCKERHUB_NAMESPACE: [DOCKERHUB_NAMESPACE]
  ALIYUN_USERNAME: [ALIYUN_USERNAME]
  ALIYUN_NAMESPACE: [ALIYUN_NAMESPACE]
  TENCENTYUN_USERNAME: [TENCENTYUN_USERNAME]
  TENCENTYUN_NAMESPACE: [TENCENTYUN_NAMESPACE]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull and push image dockerhub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker pull $SOURCE_IMAGE_NAME
        docker tag $SOURCE_IMAGE_NAME $DOCKERHUB_NAMESPACE/$TARGET_IMAGE_NAME
        docker push $DOCKERHUB_NAMESPACE/$TARGET_IMAGE_NAME
    - name: Pull and push image aliyun
      run: |
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        docker tag $SOURCE_IMAGE_NAME registry.cn-hangzhou.aliyuncs.com/$ALIYUN_NAMESPACE/$TARGET_IMAGE_NAME
        docker push registry.cn-hangzhou.aliyuncs.com/$ALIYUN_NAMESPACE/$TARGET_IMAGE_NAME
    - name: Pull and push image tencent yun
      run: |
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        docker tag $SOURCE_IMAGE_NAME ccr.ccs.tencentyun.com/$TENCENTYUN_NAMESPACE/$TARGET_IMAGE_NAME
        docker push ccr.ccs.tencentyun.com/$TENCENTYUN_NAMESPACE/$TARGET_IMAGE_NAME