name: push image and push to tencent

on:
  push:
    branches: 
      - publish_tencent

env:
  DOCKERHUB_USERNAME: [DOCKERHUB_USERNAME]
  DOCKERHUB_NAMESPACE: [DOCKERHUB_NAMESPACE]
  ALIYUN_USERNAME: [ALIYUN_USERNAME]
  ALIYUN_NAMESPACE: [ALIYUN_NAMESPACE]
  TENCENTYUN_USERNAME: [TENCENTYUN_USERNAME]
  TENCENTYUN_NAMESPACE: [TENCENTYUN_NAMESPACE]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
[ALL_IMAGE]
    steps:
    - uses: actions/checkout@v2
    - name: pull and sync
      run: |
        strings="${{ matrix.image }}"
        IFS=',' read -ra image <<< "$strings"
        $SOURCE_IMAGE_NAME=${image[0]}
        $TARGET_IMAGE_NAME=${image[1]}
        docker pull $SOURCE_IMAGE_NAME
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        docker tag $SOURCE_IMAGE_NAME ccr.ccs.tencentyun.com/$TENCENTYUN_NAMESPACE/$TARGET_IMAGE_NAME
        docker push ccr.ccs.tencentyun.com/$TENCENTYUN_NAMESPACE/$TARGET_IMAGE_NAME