name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: [DOCKERHUB_USERNAME]
  DOCKERHUB_NAMESPACE: [DOCKERHUB_NAMESPACE]
  ALIYUN_USERNAME: [ALIYUN_USERNAME]
  ALIYUN_NAMESPACE: [ALIYUN_NAMESPACE]
  TENCENTYUN_USERNAME: [TENCENTYUN_USERNAME]
  TENCENTYUN_NAMESPACE: [TENCENTYUN_NAMESPACE]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
[ALL_IMAGE]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"