name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: [DOCKERHUB_USERNAME]
  DOCKERHUB_NAMESPACE: [DOCKERHUB_NAMESPACE]
  ALIYUN_USERNAME: [ALIYUN_USERNAME]
  ALIYUN_NAMESPACE: [ALIYUN_NAMESPACE]
  TENCENTYUN_USERNAME: [TENCENTYUN_USERNAME]
  TENCENTYUN_NAMESPACE: [TENCENTYUN_NAMESPACE]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
[ALL_IMAGE]
    steps:
    - uses: actions/checkout@v2
    - name: pull and sync
      run: |
        strings="${{ matrix.image }}"
        IFS=';' read -ra image <<< "$strings"
        $SOURCE_IMAGE_NAME=${image[0]}
        $TARGET_IMAGE_NAME=${image[1]}
        docker pull $SOURCE_IMAGE_NAME
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        docker tag $SOURCE_IMAGE_NAME registry.cn-hangzhou.aliyuncs.com/$ALIYUN_NAMESPACE/$TARGET_IMAGE_NAME
        docker push registry.cn-hangzhou.aliyuncs.com/$ALIYUN_NAMESPACE/$TARGET_IMAGE_NAME