name: push image and push to tencent

on:
  push:
    branches: 
      - publish_tencent

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/vscode/devcontainers/base:0-alpine,vscode_base:0-alpine
          - mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.10,vscode_base:0-alpine-3.10
          - mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.11,vscode_base:0-alpine-3.11
          - mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.12,vscode_base:0-alpine-3.12
          - mcr.microsoft.com/vscode/devcontainers/base:0-debian,vscode_base:0-debian
          - mcr.microsoft.com/vscode/devcontainers/base:0-buster,vscode_base:0-buster
          - mcr.microsoft.com/vscode/devcontainers/base:0-debian-10,vscode_base:0-debian-10
          - mcr.microsoft.com/vscode/devcontainers/base:0-stretch,vscode_base:0-stretch
          - mcr.microsoft.com/vscode/devcontainers/base:0-debian-9,vscode_base:0-debian-9
          - mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu,vscode_base:0-ubuntu
          - mcr.microsoft.com/vscode/devcontainers/base:0-focal,vscode_base:0-focal
          - mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-20.04,vscode_base:0-ubuntu-20.04
          - mcr.microsoft.com/vscode/devcontainers/base:0-bionic,vscode_base:0-bionic
          - mcr.microsoft.com/vscode/devcontainers/base:0-ubuntu-18.04,vscode_base:0-ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        pipenv run inv docker-sync-tencent --data "${{ matrix.image }}"