name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/runtime:5.0-focal-arm64v8,runtime:5.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.6,runtime:5.0.6
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.12,runtime:5.0.6-alpine3.12
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.12-amd64,runtime:5.0.6-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.12-arm64v8,runtime:5.0.6-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.13,runtime:5.0.6-alpine3.13
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.13-amd64,runtime:5.0.6-alpine3.13-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0.6-alpine3.13-arm64v8,runtime:5.0.6-alpine3.13-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0.6-buster-slim,runtime:5.0.6-buster-slim
          - mcr.microsoft.com/dotnet/runtime:5.0.6-buster-slim-amd64,runtime:5.0.6-buster-slim-amd64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"