name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm32v7,aspnet:3.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1-focal-arm64v8,aspnet:3.1-focal-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.15,aspnet:3.1.15
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-alpine3.12,aspnet:3.1.15-alpine3.12
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-alpine3.12-arm64v8,aspnet:3.1.15-alpine3.12-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-alpine3.13,aspnet:3.1.15-alpine3.13
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-alpine3.13-arm64v8,aspnet:3.1.15-alpine3.13-arm64v8
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-bionic,aspnet:3.1.15-bionic
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-bionic-arm32v7,aspnet:3.1.15-bionic-arm32v7
          - mcr.microsoft.com/dotnet/aspnet:3.1.15-bionic-arm64v8,aspnet:3.1.15-bionic-arm64v8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"