name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/core/sdk:2.1,sdk:2.1
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810,sdk:2.1.810
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-alpine3.12,sdk:2.1.810-alpine3.12
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-bionic,sdk:2.1.810-bionic
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-bionic-arm32v7,sdk:2.1.810-bionic-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-focal,sdk:2.1.810-focal
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-focal-arm32v7,sdk:2.1.810-focal-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-stretch,sdk:2.1.810-stretch
          - mcr.microsoft.com/dotnet/core/sdk:2.1.810-stretch-arm32v7,sdk:2.1.810-stretch-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:2.1-alpine,sdk:2.1-alpine
          - mcr.microsoft.com/dotnet/core/sdk:2.1-alpine3.12,sdk:2.1-alpine3.12
          - mcr.microsoft.com/dotnet/core/sdk:2.1-bionic,sdk:2.1-bionic
          - mcr.microsoft.com/dotnet/core/sdk:2.1-bionic-arm32v7,sdk:2.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:2.1-focal,sdk:2.1-focal
          - mcr.microsoft.com/dotnet/core/sdk:2.1-focal-arm32v7,sdk:2.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:2.1-stretch,sdk:2.1-stretch
          - mcr.microsoft.com/dotnet/core/sdk:2.1-stretch-arm32v7,sdk:2.1-stretch-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1,sdk:3.1
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402,sdk:3.1.402
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-alpine3.12,sdk:3.1.402-alpine3.12
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic,sdk:3.1.402-bionic
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic-arm32v7,sdk:3.1.402-bionic-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-bionic-arm64v8,sdk:3.1.402-bionic-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-buster,sdk:3.1.402-buster
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-buster-arm32v7,sdk:3.1.402-buster-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-buster-arm64v8,sdk:3.1.402-buster-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-focal,sdk:3.1.402-focal
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-focal-arm32v7,sdk:3.1.402-focal-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1.402-focal-arm64v8,sdk:3.1.402-focal-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:3.1-alpine,sdk:3.1-alpine
          - mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.12,sdk:3.1-alpine3.12
          - mcr.microsoft.com/dotnet/core/sdk:3.1-bionic,sdk:3.1-bionic
          - mcr.microsoft.com/dotnet/core/sdk:3.1-bionic-arm32v7,sdk:3.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1-bionic-arm64v8,sdk:3.1-bionic-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:3.1-buster,sdk:3.1-buster
          - mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7,sdk:3.1-buster-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm64v8,sdk:3.1-buster-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:3.1-focal,sdk:3.1-focal
          - mcr.microsoft.com/dotnet/core/sdk:3.1-focal-arm32v7,sdk:3.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/core/sdk:3.1-focal-arm64v8,sdk:3.1-focal-arm64v8
          - mcr.microsoft.com/dotnet/core/sdk:latest,sdk:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"