name: push image and push to tencent

on:
  push:
    branches: 
      - publish_tencent

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/runtime:3.1.15-buster-slim-arm32v7,runtime:3.1.15-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1.15-buster-slim-arm64v8,runtime:3.1.15-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/runtime:3.1.15-focal,runtime:3.1.15-focal
          - mcr.microsoft.com/dotnet/runtime:3.1.15-focal-arm32v7,runtime:3.1.15-focal-arm32v7
          - mcr.microsoft.com/dotnet/runtime:3.1.15-focal-arm64v8,runtime:3.1.15-focal-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0,runtime:5.0
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine,runtime:5.0-alpine
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine-amd64,runtime:5.0-alpine-amd64
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine-arm64v8,runtime:5.0-alpine-arm64v8
          - mcr.microsoft.com/dotnet/runtime:5.0-alpine3.12,runtime:5.0-alpine3.12
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        pipenv run inv docker-sync-tencent --data "${{ matrix.image }}"