name: push image and push to aliyun

on:
  push:
    branches:
      - feature/AliyunContainerService

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update auth.config
        run: |
          cd src/GithubActionGeneration
          sed -i "s#DOCKERHUB_USERNAME#${DOCKERHUB_USERNAME}#g" config.json
          sed -i "s#DOCKERHUB_TOKEN#${DOCKERHUB_TOKEN}#g" config.json
          sed -i "s#ALIYUN_USERNAME#${ALIYUN_USERNAME}#g" config.json
          sed -i "s#ALIYUN_TOKEN#${ALIYUN_TOKEN}#g" config.json
      - name: pull and sync
        run: |
          cd src/GithubActionGeneration
          chmod a+x ./image-syncer
          ./image-syncer --auth=./auth.json --images=./images.json
