name: push image and push to dockerhub

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/sdk:2.1,sdk:2.1
          - mcr.microsoft.com/dotnet/sdk:2.1-alpine,sdk:2.1-alpine
          - mcr.microsoft.com/dotnet/sdk:2.1-alpine3.12,sdk:2.1-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:2.1-alpine3.13,sdk:2.1-alpine3.13
          - mcr.microsoft.com/dotnet/sdk:2.1-bionic,sdk:2.1-bionic
          - mcr.microsoft.com/dotnet/sdk:2.1-bionic-arm32v7,sdk:2.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1-focal,sdk:2.1-focal
          - mcr.microsoft.com/dotnet/sdk:2.1-focal-arm32v7,sdk:2.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1-stretch,sdk:2.1-stretch
          - mcr.microsoft.com/dotnet/sdk:2.1-stretch-arm32v7,sdk:2.1-stretch-arm32v7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        pipenv run inv docker-sync-dockerhub --data "${{ matrix.image }}"