name: push image and push to dockerhub

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/java/jdk:13u3-zulu-ubuntu-18.04,jdk:13u3-zulu-ubuntu-18.04
          - mcr.microsoft.com/java/jdk:13u3-zulu-ubuntu-19.10,jdk:13u3-zulu-ubuntu-19.10
          - mcr.microsoft.com/java/jdk:13u4-zulu-alpine,jdk:13u4-zulu-alpine
          - mcr.microsoft.com/java/jdk:13u4-zulu-centos,jdk:13u4-zulu-centos
          - mcr.microsoft.com/java/jdk:13u4-zulu-debian10,jdk:13u4-zulu-debian10
          - mcr.microsoft.com/java/jdk:13u4-zulu-debian9,jdk:13u4-zulu-debian9
          - mcr.microsoft.com/java/jdk:13u4-zulu-ubuntu,jdk:13u4-zulu-ubuntu
          - mcr.microsoft.com/java/jdk:13u4-zulu-ubuntu-18.04,jdk:13u4-zulu-ubuntu-18.04
          - mcr.microsoft.com/java/jdk:13u5-zulu-alpine,jdk:13u5-zulu-alpine
          - mcr.microsoft.com/java/jdk:13u5-zulu-centos,jdk:13u5-zulu-centos
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        pipenv run inv docker-sync-dockerhub --data "${{ matrix.image }}"