name: push image and push to tencent

on:
  push:
    branches: 
      - publish_tencent

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/sdk:2.1,sdk:2.1
          - mcr.microsoft.com/dotnet/sdk:2.1.812,sdk:2.1.812
          - mcr.microsoft.com/dotnet/sdk:2.1.812-alpine3.12,sdk:2.1.812-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:2.1.812-bionic,sdk:2.1.812-bionic
          - mcr.microsoft.com/dotnet/sdk:2.1.812-bionic-arm32v7,sdk:2.1.812-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1.812-focal,sdk:2.1.812-focal
          - mcr.microsoft.com/dotnet/sdk:2.1.812-focal-arm32v7,sdk:2.1.812-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1.812-stretch,sdk:2.1.812-stretch
          - mcr.microsoft.com/dotnet/sdk:2.1.812-stretch-arm32v7,sdk:2.1.812-stretch-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1-alpine,sdk:2.1-alpine
          - mcr.microsoft.com/dotnet/sdk:2.1-alpine3.12,sdk:2.1-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:2.1-bionic,sdk:2.1-bionic
          - mcr.microsoft.com/dotnet/sdk:2.1-bionic-arm32v7,sdk:2.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1-focal,sdk:2.1-focal
          - mcr.microsoft.com/dotnet/sdk:2.1-focal-arm32v7,sdk:2.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:2.1-stretch,sdk:2.1-stretch
          - mcr.microsoft.com/dotnet/sdk:2.1-stretch-arm32v7,sdk:2.1-stretch-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1,sdk:3.1
          - mcr.microsoft.com/dotnet/sdk:3.1.405,sdk:3.1.405
          - mcr.microsoft.com/dotnet/sdk:3.1.405-alpine3.12,sdk:3.1.405-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:3.1.405-bionic,sdk:3.1.405-bionic
          - mcr.microsoft.com/dotnet/sdk:3.1.405-bionic-arm32v7,sdk:3.1.405-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1.405-bionic-arm64v8,sdk:3.1.405-bionic-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1.405-buster,sdk:3.1.405-buster
          - mcr.microsoft.com/dotnet/sdk:3.1.405-buster-arm32v7,sdk:3.1.405-buster-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1.405-buster-arm64v8,sdk:3.1.405-buster-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1.405-focal,sdk:3.1.405-focal
          - mcr.microsoft.com/dotnet/sdk:3.1.405-focal-arm32v7,sdk:3.1.405-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1.405-focal-arm64v8,sdk:3.1.405-focal-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1-alpine,sdk:3.1-alpine
          - mcr.microsoft.com/dotnet/sdk:3.1-alpine3.12,sdk:3.1-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:3.1-bionic,sdk:3.1-bionic
          - mcr.microsoft.com/dotnet/sdk:3.1-bionic-arm32v7,sdk:3.1-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1-bionic-arm64v8,sdk:3.1-bionic-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1-buster,sdk:3.1-buster
          - mcr.microsoft.com/dotnet/sdk:3.1-buster-arm32v7,sdk:3.1-buster-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1-buster-arm64v8,sdk:3.1-buster-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1-focal,sdk:3.1-focal
          - mcr.microsoft.com/dotnet/sdk:3.1-focal-arm32v7,sdk:3.1-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1-focal-arm64v8,sdk:3.1-focal-arm64v8
          - mcr.microsoft.com/dotnet/sdk:5.0,sdk:5.0
          - mcr.microsoft.com/dotnet/sdk:5.0.102,sdk:5.0.102
          - mcr.microsoft.com/dotnet/sdk:5.0.102-alpine3.12,sdk:5.0.102-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:5.0.102-alpine3.12-amd64,sdk:5.0.102-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0.102-buster-slim,sdk:5.0.102-buster-slim
          - mcr.microsoft.com/dotnet/sdk:5.0.102-buster-slim-amd64,sdk:5.0.102-buster-slim-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0.102-buster-slim-arm32v7,sdk:5.0.102-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/sdk:5.0.102-buster-slim-arm64v8,sdk:5.0.102-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/sdk:5.0.102-focal,sdk:5.0.102-focal
          - mcr.microsoft.com/dotnet/sdk:5.0.102-focal-amd64,sdk:5.0.102-focal-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0.102-focal-arm32v7,sdk:5.0.102-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:5.0.102-focal-arm64v8,sdk:5.0.102-focal-arm64v8
          - mcr.microsoft.com/dotnet/sdk:5.0-alpine,sdk:5.0-alpine
          - mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12,sdk:5.0-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12-amd64,sdk:5.0-alpine3.12-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0-alpine-amd64,sdk:5.0-alpine-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim,sdk:5.0-buster-slim
          - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-amd64,sdk:5.0-buster-slim-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7,sdk:5.0-buster-slim-arm32v7
          - mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm64v8,sdk:5.0-buster-slim-arm64v8
          - mcr.microsoft.com/dotnet/sdk:5.0-focal,sdk:5.0-focal
          - mcr.microsoft.com/dotnet/sdk:5.0-focal-amd64,sdk:5.0-focal-amd64
          - mcr.microsoft.com/dotnet/sdk:5.0-focal-arm32v7,sdk:5.0-focal-arm32v7
          - mcr.microsoft.com/dotnet/sdk:5.0-focal-arm64v8,sdk:5.0-focal-arm64v8
          - mcr.microsoft.com/dotnet/sdk:latest,sdk:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        pipenv run inv docker-sync-tencent --data "${{ matrix.image }}"