name: push image and push to dockerhub

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/mssql/server:2017-CU10-ubuntu,server:2017-CU10-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU11-ubuntu,server:2017-CU11-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU12-ubuntu,server:2017-CU12-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU13-ubuntu,server:2017-CU13-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU14-ubuntu,server:2017-CU14-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU15-ubuntu,server:2017-CU15-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU16-ubuntu,server:2017-CU16-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU17-ubuntu,server:2017-CU17-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU18-ubuntu-16.04,server:2017-CU18-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2017-CU19-ubuntu-16.04,server:2017-CU19-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2017-CU1-ubuntu,server:2017-CU1-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04,server:2017-CU20-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04,server:2017-CU21-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2017-CU2-ubuntu,server:2017-CU2-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU3-ubuntu,server:2017-CU3-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU4-ubuntu,server:2017-CU4-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU5-ubuntu,server:2017-CU5-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU6-ubuntu,server:2017-CU6-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU7-ubuntu,server:2017-CU7-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU8-ubuntu,server:2017-CU8-ubuntu
          - mcr.microsoft.com/mssql/server:2017-CU9-ubuntu,server:2017-CU9-ubuntu
          - mcr.microsoft.com/mssql/server:2017-GA-ubuntu,server:2017-GA-ubuntu
          - mcr.microsoft.com/mssql/server:2017-GDR-ubuntu,server:2017-GDR-ubuntu
          - mcr.microsoft.com/mssql/server:2017-latest,server:2017-latest
          - mcr.microsoft.com/mssql/server:2019-CU1-ubuntu-16.04,server:2019-CU1-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04,server:2019-CU2-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-16.04,server:2019-CU3-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04,server:2019-CU4-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04,server:2019-CU5-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04,server:2019-CU6-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04,server:2019-GA-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-GDR1-ubuntu-16.04,server:2019-GDR1-ubuntu-16.04
          - mcr.microsoft.com/mssql/server:2019-latest,server:2019-latest
          - mcr.microsoft.com/mssql/server:latest,server:latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        pipenv run inv docker-sync-dockerhub --data "${{ matrix.image }}"