name: push image and push to aliyun

on:
  push:
    branches: 
      - publish

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/java/jre:15u1-zulu-ubuntu-18.04,jre:15u1-zulu-ubuntu-18.04
          - mcr.microsoft.com/java/jre:15u2-zulu-alpine,jre:15u2-zulu-alpine
          - mcr.microsoft.com/java/jre:15u2-zulu-centos,jre:15u2-zulu-centos
          - mcr.microsoft.com/java/jre:15u2-zulu-debian10,jre:15u2-zulu-debian10
          - mcr.microsoft.com/java/jre:15u2-zulu-debian9,jre:15u2-zulu-debian9
          - mcr.microsoft.com/java/jre:15u2-zulu-ubuntu,jre:15u2-zulu-ubuntu
          - mcr.microsoft.com/java/jre:15u2-zulu-ubuntu-18.04,jre:15u2-zulu-ubuntu-18.04
          - mcr.microsoft.com/java/jre:15u3-zulu-alpine,jre:15u3-zulu-alpine
          - mcr.microsoft.com/java/jre:15u3-zulu-centos,jre:15u3-zulu-centos
          - mcr.microsoft.com/java/jre:15u3-zulu-debian10,jre:15u3-zulu-debian10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.ALIYUN_TOKEN }}" | docker login -u $ALIYUN_USERNAME --password-stdin registry.cn-hangzhou.aliyuncs.com
        pipenv run inv docker-sync-aliyun --data "${{ matrix.image }}"