name: push image and push to tencent

on:
  push:
    branches: 
      - publish_tencent

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - mcr.microsoft.com/dotnet/sdk:3.1.409-alpine3.12,sdk:3.1.409-alpine3.12
          - mcr.microsoft.com/dotnet/sdk:3.1.409-alpine3.13,sdk:3.1.409-alpine3.13
          - mcr.microsoft.com/dotnet/sdk:3.1.409-bionic,sdk:3.1.409-bionic
          - mcr.microsoft.com/dotnet/sdk:3.1.409-bionic-arm32v7,sdk:3.1.409-bionic-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1.409-bionic-arm64v8,sdk:3.1.409-bionic-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1.409-buster,sdk:3.1.409-buster
          - mcr.microsoft.com/dotnet/sdk:3.1.409-buster-arm32v7,sdk:3.1.409-buster-arm32v7
          - mcr.microsoft.com/dotnet/sdk:3.1.409-buster-arm64v8,sdk:3.1.409-buster-arm64v8
          - mcr.microsoft.com/dotnet/sdk:3.1.409-focal,sdk:3.1.409-focal
          - mcr.microsoft.com/dotnet/sdk:3.1.409-focal-arm32v7,sdk:3.1.409-focal-arm32v7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: pull and sync
      run: |
        cd src/GithubActionGeneration
        pip install pipenv
        pipenv install
        pipenv run inv pull-image --data "${{ matrix.image }}"
        echo "${{ secrets.TENCENTYUN_TOKEN }}" | docker login -u $TENCENTYUN_USERNAME --password-stdin ccr.ccs.tencentyun.com
        pipenv run inv docker-sync-tencent --data "${{ matrix.image }}"